baseURL: https://undeconstructed.github.io/vortejo/
languageCode: eo
DefaultContentLanguage: eo
title: Vortejo
disableKinds: [ "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT" ]
menu:
  after:
  - name: Datumoj
    url: https://undeconstructed.github.io/vortaro/
    weight: -110
params:
  vortaroURL: /vortejo/vortaro
